services:
  - type: web
    name: quiz-platform-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: quiz-platform-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: quiz-platform-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: quiz-platform-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: quiz-platform-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: quiz-platform-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080

databases:
  - name: quiz-platform-db
    databaseName: quiz_platform
    user: quiz_platform
    plan: free 