services:
  - type: web
    name: quiz-platform-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d14ib7h5pdvs73f77kdg-a/quiz_platform_db
      - key: DB_USER
        value: quiz_platform_db_user
      - key: DB_PASSWORD
        value: EZ8IhYi0YV4G19zHmYmGE6kN4Rgkdj7d
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080

databases:
  - name: quiz-platform-db
    databaseName: quiz_platform_db
    user: quiz_platform_db_user
    plan: free 