services:
  - type: web
    name: quiz-platform-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-platform-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080

databases:
  - name: quiz-platform-db
    databaseName: quiz_platform_db
    user: quiz_platform_db_user
    plan: free 